# ==============================================================================
# STANDALONE TARGET CONFIGURATION
# ==============================================================================
# This configuration sets up a target device in standalone mode.
# In standalone mode, the target operates independently without requiring
# a central controller or Home Assistant integration.
# ==============================================================================


# ==============================================================================
# NETWORK CONFIGURATION - STANDALONE MODE (AP ONLY)
# ==============================================================================
wifi:
  # Force AP-only mode - do not connect to any networks
  networks: []     # Empty networks list
  
  # Explicitly disable station mode
  enable_on_boot: true
  fast_connect: false
  
  # AP configuration for standalone mode  
  ap:
    ssid: "${name}"
    password: "target123"
    ap_timeout: 1min
  
  # Disable station mode and prevent network scanning
  reboot_timeout: 0s        # Disable auto-reboot on WiFi loss  
  power_save_mode: none     # Disable power saving for reliability
  output_power: 20dB        # Maximum WiFi power for best range
  passive_scan: true        # Reduce active network scanning
  
  on_connect:
    then:
      - logger.log: "WiFi AP mode activated"

# ==============================================================================
# NETWORK & WEB INTERFACE - Common Services
# ==============================================================================
web_server: # Target web page
  port: 80
  include_internal: false
  local: true
  css_include: "boards/common/custom.css"
  js_include: "boards/common/custom.js"
  version: 2